# Generated by Django 5.2.7 on 2025-10-15 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_content_article_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
    ]
