# Generated by Django 5.2.7 on 2025-10-15 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_remove_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50)]),
        ),
    ]
